apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiohttp-websockets.fullname" . }}
  labels:
    {{- include "aiohttp-websockets.labels" . | nindent 4 }}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"{{ include "aiohttp-websockets.fullname" . }}-config"}}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aiohttp-websockets.selectorLabels" . | nindent 4 }}
